### PR TITLE
Make compile with MSVC 2015

### PR DESCRIPTION
**Pull request by a-ilin**
This patchset contains changes needed to compile unshield at Windows with MSVC 2015.
It is successfully compiles and works.

I tested linkage with OpenSSL and zlib.

### CODE REVIEW

**Comment by twogood** [comment]
Very nice, thank you! But I'm afraid the WIN32 checks in CMakeLists.txt (e.g. `if(WIN32)`) and in the source code (e.g. `#if defined(_WIN32) || defined(_WIN64)` will break MinGW support.... ping @xantares !

**Comment by xantares** [comment]
yep, these flags you set in CMakeLists are msvc specific, so it should be if(MSVC), then the *printf fixes are not needed with mingw to you should check that "__MINGW32__" is not defined

**Comment by twogood** [comment]
Thanks a lot @xantares for your quick and concise response. @a-ilin would you update the PR so that it builds on both MinGW and MSVC?

**Comment by a-ilin** [comment]
Thanks for the notices! I made the changes, however I have no possibility to check the build against MinGW.

**Comment by twogood** [comment]
@xantares Are you able to test this PR with MinGW?

**Comment by xantares** [comment]
Yes it's building fine.
But ```if (WIN32 AND MSVC)``` is redundant, do just ```if (MSVC)```
On a side note you also would make sure these warnings are fixed:
```
/home/xantares/projects/unshield/src/unshield.c: In function ‘make_sure_directory_exists’:
/home/xantares/projects/unshield/src/unshield.c:104:13: warning: implicit declaration of function ‘_mkdir’ [-Wimplicit-function-declaration]
         if (_mkdir(current) < 0)
             ^~~~~~
/home/xantares/projects/unshield/src/unshield.c: In function ‘extract_file’:
/home/xantares/projects/unshield/src/unshield.c:457:1: warning: label ‘exit’ defined but not used [-Wunused-label]
 exit:
 ^~~~
/home/xantares/projects/unshield/src/unshield.c: In function ‘list_files_helper’:
/home/xantares/projects/unshield/src/unshield.c:610:18: warning: unknown conversion type character ‘z’ in format [-Wformat=]
       printf(" %8" SIZE_FORMAT "  %s%s\n",
                  ^
/home/xantares/projects/unshield/src/unshield.c:610:14: warning: format ‘%s’ expects argument of type ‘char *’, but argument 2 has type ‘size_t {aka unsigned int}’ [-Wformat=]
       printf(" %8" SIZE_FORMAT "  %s%s\n",
              ^~~~~
/home/xantares/projects/unshield/src/unshield.c:610:14: warning: too many arguments for format [-Wformat-extra-args]
/home/xantares/projects/unshield/src/unshield.c: In function ‘extract_file’:
/home/xantares/projects/unshield/src/unshield.c:458:6: warning: ‘success’ may be used uninitialized in this function [-Wmaybe-uninitialized]
   if (!success)
      ^
```

**Comment by twogood** [comment]
Thanks @xantares for your help! @a-ilin do you see the same warnings?

By the way, this is incorrect even if it gives the expected output :-)
```
#ifndef __PRETTY_FUNCTION__
#define __PRETTY_FUNCTION__ __FUNCTION__
#endif
```

As `__PRETTY_FUNCTION__` is undefined outside of a function, it will always be redefined to __FUNCTION__, but that's not a problem as __PRETTY_FUNCTION__ seems to be the same as __FUNCTION__ in C. Maybe I used it of habit from of my C++ days... :-)

So maybe I should replace all __PRETTY_FUNCTION__ with __FUNCTION__ in a separate patch?

**Comment by a-ilin** [comment]
Thanks for replies!
@twogood, macro __PRETTY_FUNCTION__ is undefined at MSVC so using it produces a corresponding error. That define fixes it.

**Comment by twogood** [comment]
@a-ilin : You can remove the `__PRETTY_FUNCTION__` stuff from `lib/internal.h` in your PR now! :-)

**Comment by twogood** [comment]
Ping @a-ilin :-)

**Comment by a-ilin** [comment]
Thanks, @twogood!
Unfortunately I'm quite busy right now, so I will fix the patchset in a couple of weeks.

**Comment by mirh** [comment]
Rebase and merge?

**Comment by twogood** [comment]
New PR: #81

**Pull request closed without merging**
