### PR TITLE
libunshield: use OpenWall's md5.c and make it the only option

### PR DESCRIPTION
**Pull request by wdlkmpx**

### CODE REVIEW

**Comment by wdlkmpx** [comment]
Even the creator of e2fsprogs uses this md5.c instead of openssl. It means that it's quite safe, Linux is an OS that also runs on big endian machines.

https://patchwork.kernel.org/project/fstests/patch/20170525174134.6276-1-tytso@mit.edu/

> Use Solar Designer's openssl compatible implementation of md5 so we no longer need to depend on OpenSSL.
> The other problem with depending on the OpenSSL libraries is that shared library compatibility situation is terrible; a fssum binary built on a system using libssl1.0.0 is *NOT* run on a system with libssl1.0.2, since the shared libraries are incompatible even across a minor version bump.  (Sigh.)

A google search reveals that in recent years more and more apps are using this md5 implementation, so it's trusted.

By the way support for big endian machines is broken in libunshield, that is fixed in another PR (finish transition from autotools to cmake).

So I humbly request @twogood to merge this, you will not regret it. I take full responsibility for fixing issues that may arise (symbol collision, they have to report it first...) or revert this change whenever is needed/requested..

**Comment by wdlkmpx** [comment]
I didn't close these pull requests, only deleted the branches. I opened pull requests before and deleted the branches, and the PR's remained open.

It's the first time I'm seeing this abnormal Github behavior.

At least now I know that from now on I must not delete branches with open pull requests.

I think the repo owner can still reopen and merge, this change is also in the master branch of my repo along with many other changes.

**Comment by twogood** [comment]
I was wondering what happened @wdlkmpx  :)

**Comment by wdlkmpx** [comment]
This md5 is quite solid, unlike miniz which is not truly compatible with zlib

All the UNIX Travis tests pass (linux,freedbsd,macos) be/le, the full test suite (run-tests).

The Windows stuff has been improved, the problem with MinGW is that the printf stuff is a mess (msvcrt vs gnu)
https://travis-ci.com/github/wdlkmpx/unshield/jobs/506186755

The MSVC build looks better, I'll fix -Wextra gcc warnings that may also fix some MSVC warnings
https://travis-ci.com/github/wdlkmpx/unshield/jobs/506186756

The only thing that's missing in the windows builds is iconv.

At one point I'll move onto something else, so I recommend keeping an eye on my repo, which only enhances test infrastructure and improves compatibility/stability between systems.

**Comment by twogood** [comment]
I'd love to merge this md5. I never got any iconv working on Windows...

**Comment by wdlkmpx** [comment]
I'll open a massive pull request one of these days, I think all my changes are equally important for this project, and most of those changes are as big as this.

I only need to show the build logs to prove that everything works and better than before.

I'll also try to add iconv for windows, it's a huge lib. I'll take the musl lib C implementation to provide a somewhat limited icon support if the system/lib iconv is not found.

**Pull request closed without merging**
