### PR TITLE
Refactored libunshield CMakeLists to build on windows

### PR DESCRIPTION
**Pull request by twogood**
Create pull request to see if Travis and Appveyor picks it up

### CODE REVIEW

**Comment by kpyrkosz** [comment]
Spent some time digging in appveyor docs and i found out how to have separate linux and windows configs in two different yaml files. It is possible to set up the CI for the same repo twice, with different `Custom configuration .yml file name` file set to `.appveyor-windows.yml` in first case and `.appveyor-linux.yml` in second. This is particularly convenient because the build procedure in both cases is diametrally different, splitting into two per-OS configurations makes it more readable and smaller. This is how it looks in practice:
https://ci.appveyor.com/project/kpyrkosz/unshield-windows
https://ci.appveyor.com/project/kpyrkosz/unshield-linux

Notice that the build above (in this PR) still uses the old script.
I've restored your original travis file so it does not contain any of my modifications, the branch is mergable.

**Comment by twogood** [comment]
Excellent work!!!

Thanks! I'll try to sort this out ASAP but I'm in a busy period right now.

**Comment by kpyrkosz** [comment]
Any progress? :)

**Comment by twogood** [comment]
Thank you for the kind reminder @kpyrkosz. Maybe just merge? :) 

PS. I heard Travis-ci is closing down their .org and we have to migrate to their .com version...

**Comment by kpyrkosz** [comment]
Yes, you can merge, is there any obstacle in the way?

**Comment by twogood** [comment]
Damn, I shouldn't have squashed it, now I get the git blame....

**Pull request merged**
