### PR TITLE
always use the internal md5c.c

### PR DESCRIPTION
**Pull request by wdlkmpx**
* always use the internal md5c.c
    
 remove references to openssl
 simplify builds/configs

* lib: do not create a separate md5 static lib
 
 simplify cmake stuff even more

Technically, the 2nd commit belongs to another PR, but it's already done

### CODE REVIEW

**Comment by wdlkmpx** [comment]
This looks like a newer md5.c/.h ... smaller, doesn't have global.h (PROTO_LIST, POINTER)
https://github.com/yingshirun/Android-NDK-MD5/tree/master/app/src/main/jni

It could replace the current file,

**Comment by wdlkmpx** [comment]
I adapted the md5.c from the android ndk and unsurprisingly all the checks pass.

There is absolutely no reason to use the openssl libs, cabextract uses its internal md5.c (taken from GNU Libc), which is more complex and has big endian/little endian stuff and 100 #ifdefs, this one is better.

For md5, sha1, sha256, crc32, there are very small libs and single header files, there is no reason to complicate the build, the more static a build is, the more targets will compile out of the box.

I think the static md5 might add 5kb to the lib, that's nothing.

I was also testing with a static miniz (zlib drop-in replacement), and libunshield basically becomes smaller.

**Comment by twogood** [comment]
Sounds good @wdlkmpx ! But will this work on ARM if it does not have specific big/small endian code?

**Comment by twogood** [comment]
The problem with the internal MD5 is the licensing I believe. I don't think it is MIT-compatible.

**Comment by wdlkmpx** [comment]
I'm sure it works in the raspis, I had raspi 1, but it died. But I'm sure it works. I'm sure some other app with this md5.c is running on a raspi right now.

This project is not GPL, MIT is a permissive license, it accepts everything.

The problem is GPL, and the other problem is Debian. They forked cdrtools because it was CDDL (free opensource software), their fork (cdrkit) is buggy as hell while cdrtools is the best cd/dvd/bd burning tool for linux.

**Comment by twogood** [comment]
Not only RPi, the Mac M1 too

**Comment by twogood** [comment]
By the way, the AppVeyor builds say they succeed even when they are broken (like all the time)

**Comment by wdlkmpx** [comment]
I read a bit, and basically all machines running Windows & Linux are little endian. That's about 99% of users of this app.

But IBM mainframes, HPUX and big server stuff are big endian. So basically big endian IS outside the realms of normality.
Maybe there will be problems with "Macintosh" or something.

Probably this md5.c is only optimized for little endian machines, this is pure speculation, it might work in both big/little endian machines.
 
I found this, the same md5.c file, but modified to use little/big endian stuff:
http://www.efgh.com/software/md5.htm

It renames MD5_CTX to MD5 and who knows what else, those changes should be reverted.
Also, the code ithat ncludes md5.h must define LITTLE_ENDIAN, something like this:
https://github.com/dvidelabs/flatcc/blob/master/include/flatcc/portable/pendian_detect.h

**Comment by wdlkmpx** [comment]
I think the current md5.c is somewhat "safe".  think it works in both LE/BE

```c
  Decode (x, block, 64);

....
static void Decode (UINT4 *output, unsigned char *input, unsigned int len)
{
  unsigned int i, j;

  for (i = 0, j = 0; j < len; i++, j += 4)
 output[i] = ((UINT4)input[j]) | (((UINT4)input[j+1]) << 8) |
   (((UINT4)input[j+2]) << 16) | (((UINT4)input[j+3]) << 24);
}
```

vs LE/BE md5.c

```c
  #ifdef LITTLE_ENDIAN
    memcpy(x, block, 64);
  #else
  {
    unsigned int i, j;
    for (i = j = 0; i < 16; i++, j+= 4)
    {
      x[i] = (UINT4) block[j] | (UINT4) block[j+1] << 8 |
        (UINT4) block[j+2] << 16 | (UINT4) block[j+3] << 24;
    }
  }
  #endif

```

**Comment by wdlkmpx** [comment]
LE/BE md5.c: https://github.com/wdlkmpx/unshield/commit/43f9130956aa5aacab91aada74b157208094ff30
triggers one CodeQL warning in CPP mode.

But I believe the Android NDK version is the one to use, I guess it has been audited and simplified a bit and I believe it is endian-independent code.

It's pretty generic code that compiles and works everywhere.

The musl md5 implemention also seems to be endian-independent
http://git.musl-libc.org/cgit/musl/tree/src/crypt/crypt_md5.c

No #ifdefs, I guess the musl md5.c is another good candidate, musl compiles and runs in all kinds of processor architectures.

**Comment by wdlkmpx** [comment]
This looks like the perfect version, a drop-in replacement and PUBLIC DOMAIN:
https://openwall.info/wiki/people/solar/software/public-domain-source-code/md5
https://cvsweb.openwall.com/cgi/cvsweb.cgi/Owl/packages/popa3d/popa3d/md5/md5.c?rev=1.15;content-type=text%2Fplain

**Comment by wdlkmpx** [comment]
I decided to use OpenWall's md5.c. I ran all the tests in `test/v0` and I see no warnings, exit code 0.
I extracted a couple InstallShield cab files from some old printer drivers, I see no issues. How to test this reliably...

That's all on my side. Expecting the right people to test this PR, we will have to wait a few years. People usually only test code that is already merged.

But here is the snapshot:
[unshield-md5.zip](https://github.com/twogood/unshield/files/6184228/unshield-md5.zip)

Tested OpenSSL-compatible md5 versions that work OOTB, just replace md5.c/.h:
[unshield_md5_android_ndk.zip](https://github.com/twogood/unshield/files/6184233/unshield_md5_android_ndk.zip)
[unshield_md5_OpenWall.zip](https://github.com/twogood/unshield/files/6184234/unshield_md5_OpenWall.zip)
[unshield_md5_orig.zip](https://github.com/twogood/unshield/files/6184235/unshield_md5_orig.zip)
[unshield_md5_rsa_endian.zip](https://github.com/twogood/unshield/files/6184236/unshield_md5_rsa_endian.zip)

The AppVeyor build fails due to unresolved symbols, I think I have an answer to that, compiling zlib support directly into libunshield.

**Comment by twogood** [comment]
What if someone is linking libunshield from another application? Won't this cause a name clash if they also link with another MD5 library?

**Comment by wdlkmpx** [comment]
I don't think so, I'm not really sure how the whole thing works, but there are scopes... for example including headers with function definitions (not only declarations) will compile the same code for each .c file that includes it. creating duplicate binary stuff.

A good example should be trying to integrate libunshield into cabextract.

But renaming the shared declarations between the md5/file.c (MD5_Init to _MD5_Init)  should prevent any possible issue, it's also possible to rename all the md5 functions. I can do that if you want.

There are 4 possible variants, so it's possible to try other variant and see if it's more suitable.

I take full responsibility for this and will make the requested changes to prevent issues and can also revert de the whole thing in a matter of minutes.

**Pull request closed without merging**
