### PR TITLE
git lfs test

### PR DESCRIPTION
**Pull request by twogood**

### CODE REVIEW

**Comment by twogood** [comment]
@kratz00 use LFS like this?

**Comment by kratz00** [comment]
In case there are just cab files I would directly add them, the Zip is just overhead (does not save disk space either).
The only exception I currently see is the *wireplay* Zip file, as most data files from it are needed.

**Comment by twogood** [comment]
> In case there are just cab files I would directly add them, the Zip is just overhead (does not save disk space either). The only exception I currently see is the _wireplay_ Zip file, as most data files from it are needed.

One of the reasons for having .zip files is to make it harder for DMCA scanning bots and similar crap, in case there would be a match.

**Comment by kratz00** [comment]
Understood, I will update my PR and put the cab files into Zip files again.

**Comment by kratz00** [comment]
@twogood I disabled the crashing test for now (see issue #156) to unblock this pull request.

**Comment by twogood** [comment]
Fixed in #149

**Pull request closed without merging**
