### PR TITLE
Fix for binary files.

### PR DESCRIPTION
**Pull request by Djamana**
Else files are opened in Text mode and get chopped on each 0x1c byte that means EOF.

### CODE REVIEW

**Comment by twogood** [comment]
Thank you! Could you please split in multiple pull requests? At least one for binary mode and another for Visual Studio fixes?

**Comment by Djamana** [comment]
Well I had the same in mind. ;^)

But I'm sorry it some just got one big one.
(At least there is 'Fix to make it work for binary file.' commit. inside it.)

I'm new to github and still a little clumsy. ...and happy to get it done at least somehow.
(I'm also just getting into cmake...)

I hope you can also use it like this. I'm a little scared to mess things.

**Comment by bugmenot2** [comment]
Hi @twogood and @Djamana, thanks for fixing the deobfuscate tool... uh... did you forget something? :stuck_out_tongue:
```diff
 lib/file.c | 6 +++---
 1 file changed, 3 insertions(+), 3 deletions(-)

diff --git a/lib/file.c b/lib/file.c
index dce530b..2dc7969 100644
--- a/lib/file.c
+++ b/lib/file.c
@@ -689,7 +689,7 @@ bool unshield_file_save (Unshield* unshield, int index, const char* filename)/*{
 
   if (filename) 
   {
-    output = fopen(filename, "w");
+    output = fopen(filename, "wb");
     if (!output)
     {
       unshield_error("Failed to open output file '%s'", filename);
@@ -891,7 +891,7 @@ bool unshield_file_save_raw(Unshield* unshield, int index, const char* filename)
 
   if (filename) 
   {
-    output = fopen(filename, "w");
+    output = fopen(filename, "wb");
     if (!output)
     {
       unshield_error("Failed to open output file '%s'", filename);
@@ -1008,7 +1008,7 @@ bool unshield_file_save_old(Unshield* unshield, int index, const char* filename)
 
   if (filename) 
   {
-    output = fopen(filename, "w");
+    output = fopen(filename, "wb");
     if (!output)
     {
       unshield_error("Failed to open output file '%s'", filename);
```

**Comment by twogood** [comment]
@bugmenot2 : well... divide and conquer?

**Comment by twogood** [comment]
@bugmenot2: check master now! :-)

**Pull request closed without merging**
