### PR TITLE
win32_msvc/getopt.h: use getopt_long from ya_getopt

### PR DESCRIPTION
**Pull request by wdlkmpx**
ya_getopt.c + ya_getopt.h = getopt.h

https://github.com/kubo/ya_getopt

### CODE REVIEW

**Comment by wdlkmpx** [comment]
I tested this getopt.h ... compiles and works fine on Debian, but ya_getopt is also supposed to compile on Windows.

This should be merged only if @Florin9doi confirms it works on Windows (`unshield --version`)
[getopt.zip](https://github.com/twogood/unshield/files/6445007/getopt.zip)

**Comment by Florin9doi** [comment]
It works

Untitled

**Comment by wdlkmpx** [comment]
`win32_msvc/getopt.h` is only used if MSVC is detected, but for my test, I placed geptopt.h in src/ and edited src/unshield.c: `<geptopt.h>` -> `"getopt.h"`
The code looks like pure ANSI C and uses `ya_` prefix for everything, portable as hell..

**Comment by twogood** [comment]
Everyone is happy  (except Travis)?

**Comment by wdlkmpx** [comment]
Something is wrong with the Travis build, but it's unrelated to this PR, or so I think. 

```
The following packages have unmet dependencies:

 clang : Depends: clang-10 (>= 10~) but it is not going to be installed

E: Unable to correct problems, you have held broken packages.
apt-get.diagnostics

apt-get install failed

The command "sudo -E apt-get -yq --no-install-suggests --no-install-recommends $(travis_apt_get_options) install clang" failed and exited with 100 during .
```

It's not like getopt.h is required for aptget to process packages correctly..
unless a build is triggered on some other PR or branch to see if it only happens here

**Comment by twogood** [comment]
Travis could buld the master branch on Linux 16 days ago but the Mac build has been broken a long time.

**Comment by wdlkmpx** [comment]
In pr #296 I triggerd a build by force-pushing changes, the Travis tests pass but the failures are the same
https://travis-ci.org/github/twogood/unshield/jobs/770209167

It's safe to ignore the Travis build, it needs fixing. It should be simplified and only use gcc to compile. clang is a huge package. I don't have it installed in my lightweight distro.

**Comment by wdlkmpx** [comment]
I think this PR is safe to merge, the Travis Linux builds were verified to be broken, it's something the Travis Team must fix, since using another ubuntu version works. 

It fixes an issue that only affects MSVC, something I broke. I'm trying to fix something I broke, I repeat I'm trying to fix something I broke.

It has been properly tested by someone using MSVC. After this PR is merged @Florin9doi  might also want to test PR #114 (extracting files), I think it also works on any macOS arch (FreeType uses OW's md5).

**Pull request merged**
