### PR TITLE
no mkdir flags on mingw

### PR DESCRIPTION
**Pull request by xantares**

### CODE REVIEW

**Comment by twogood** [comment]
I would actually prefer an autoconf check for this via http://www.gnu.org/software/autoconf-archive/ax_func_mkdir.html - just create a subdirectory with ax_func_mkdir.m4 and add the #if statement after the includes in unshield.c.

**Comment by xantares** [comment]
overengineered with autoconf, exactly!

**Comment by twogood** [comment]
True, but maybe at least _mkdir and not mkdir should be used in the MinGW case?

**Comment by xantares** [comment]
no, mkdir is defined too, I checked.

**Comment by twogood** [comment]
I believe that on Windows it is preferred to use _mkdir to specify that it's a Windows call and not the two-parameter POSIX mkdir call.

**Comment by xantares** [comment]
ok

**Comment by twogood** [comment]
Thanks! Does this compile for you or do you also need to include direct.h?

**Comment by xantares** [comment]
it does compile. mkdir and _mkdir are both defined in direct.h, must be included somehow.

**Comment by twogood** [comment]
Excellent!

**Comment by twogood** [comment]
Thank you very much!

**Pull request merged**
